// Complete localized dictionary for total English & Burmese translation sync
export const dict = {
  en: {
    appName: "Sales Brain AI",
    smeHubTab: "SME HUB",
    subtitle: "",
    webhooksActive: "Webhooks Active",
    editBusinessProfile: "Edit Profile Info",
    catalogItems: "Catalog items",
    resetDemoState: "Reset Demo State",
    liveBot: "Live Bot",
    defaultBotWarn: "",
    totalStoreRevenue: "Total Store Revenue",
    excludesDelivery: "",
    validatedOrders: "Validated Orders",
    cashOnDeliveryAndPrepay: "",
    needsVerification: "Needs Verification",
    pendingOwnerVerification: "",
    stockWarnings: "Stock Warnings",
    lowStockMsg: "",
    allInventoriesHealthy: "All inventories healthy",
    webhookAlertTitle: "New Payment Receipt Proof ({count})",
    webhookAlertBody: "Owner validation required.",
    reviewReceipts: "Review Receipts now",
    pendingTransactionsLedger: "PENDING TRANSACTIONS & SALES LEDGER",
    validateSubmittedScreenshots: "",
    exportLedgerCsv: "Export Ledger CSV",
    orderInvoice: "Order Invoice",
    clientCustomer: "Client Customer",
    addressLocation: "Address Location",
    paymentMethod: "Payment Method",
    status: "Status",
    invoiceSum: "Invoice Sum",
    receiptVerification: "Receipt Verification",
    evaluateReceiptHeader: "TRANSACTION EVALUATOR & VERIFICATION PREVIEW",
    evaluateReceipt: "Evaluate Receipt",
    approveCod: "Approve COD order",
    markCompleted: "Mark Completed",
    noAuditNeeded: "No audit action needed",
    lowStockTag: "LOW STOCK",
    unitPriceMmk: "Unit Price (MMK)",
    stockLevel: "Stock level",
    invoiceRef: "Invoice Reference",
    transactionId: "Transaction ID",
    paymentChannel: "Payment Channel",
    totalCharged: "Total Charged",
    confirmGenerateInvoice: "Confirm & Generate Invoice",
    rejectScreenshot: "Reject Screenshot",
    closeEvalPane: "Close evaluation pane",
    submittedScreenshotEvidence: "Submitted Screenshot Evidence:",
    premiumStoreCatalog: "PREMIUM STORE CATALOGUE",
    controlProductPrices: "",
    addNewProduct: "Add New Product",
    editInfo: "Edit Info",
    delete: "Delete",
    editProductHeader: "EDIT PRODUCT",
    addNewProductHeader: "ADD NEW PREMIUM PRODUCT",
    brandNameLabel: "Product Brand Name:",
    categoryLabel: "Category:",
    unitPriceLabel: "Unit Price (MMK):",
    availableStockLabel: "Available stock quantity:",
    imageUrlLabel: "Product Image File:",
    shortDescriptionLabel: "Short Description details:",
    confirmProductRevisions: "Confirm product revisions",
    addItemCatalog: "Add item catalog",
    townshipDeliveryRateMatrix: "TOWNSHIP DELIVERY RATE MATRIX",
    defineDeliveryFees: "",
    townshipNameLabel: "Township Name in Yangon:",
    rateLabel: "Rate (MMK):",
    addRateRule: "Add rate rule",
    matchedTownship: "Matched Township",
    estimatedTransit: "Estimated transit timeline",
    settingsActions: "Settings Actions",
    removeRule: "Remove Rule",
    weeklyStoreVolume: "Weekly store checkout volume",
    leanAccountingStatsSummary: "LEAN ACCOUNTING STATS SUMMARY",
    grossSalesValue: "Gross sales value:",
    ordersCompiled: "Orders compiled:",
    canceledTransactions: "Canceled transactions:",
    downloadLedgerCsv: "Download Ledger CSV Report",
    salesBrainAdvisorDesk: "SALES BRAIN AI ADVISOR DESK",
    strategicAnalysisPoweredBySparkles: "",
    reEvaluateStrategy: "Re-evaluate strategy",
    analyzingPatterns: "Sales Brain is analyzing customer patterns...",
    telegramBotActivationWorkspace: "TELEGRAM BOT ACTIVATION WORKSPACE",
    oneClickOnboardingDesc: "",
    storeNameLabel: "Store Name:",
    smeOwnerNameLabel: "SME Owner Name:",
    contactPhoneLabel: "Contact Phone Number:",
    customBotTokenLabel: "Custom Bot Token ID:",
    setViaBotFather: "Set via @BotFather",
    telegramBotUsernameLabel: "Telegram Bot Username (@):",
    saveStoreSettingsBtn: "SAVE STORE SETTINGS AND ACTIVATED TELEGRAM VIRTUAL DEPLOY",
    liveSupportRoomHeader: "SME CRM LIVE SUPPORT ROOM",
    chatTakeoverDesc: "",
    activeUserSessionsLabel: "ACTIVE USER SESSIONS:",
    supportLabel: "SUPPORT",
    aiAutoLabel: "AI AUTO",
    noMessagesChosen: "No messages chosen",
    activeModeLabel: "Active mode:",
    manualSupportOverrideLabel: "Manual Support Override",
    automatedBotActiveLabel: "Automated Bot active",
    turnOnAiBotLabel: "Turn On AI Bot Agent",
    switchToManualLabel: "Switch to Manual Mode",
    ownerChatInputPlaceholder: "Chat direct with client here...",
    takeoverPlaceholder: "Takeover session to text with customers personally...",
    sendMessageBtn: "Send Message",
    integrationQuickGuidance: "INTEGRATION QUICK GUIDANCE",
    quickGuidanceExplanation: "SME shop owners add/delete items in the left Product Matrix, adjust Delivery Matrix, and click the chat buttons on the right inside our simulator. Chat responses are produced immediately.",
    viewSimulatorButton: "Simulate Customer Chat",
    closeSimulatorButton: "Hide Chat Simulator",
    simulationSandboxTitle: "Telegram Sandbox Client Simulator",
    chooseLanguageLabel: "Language / ဘာသာစကား",
    tabOrders: "Orders Ledger",
    tabProducts: "Product Catalog",
    tabDelivery: "Delivery Matrix",
    tabInsights: "AI Strategy",
    tabSmartMarketing: "Smart Marketing",
    tabConfig: "Bot Connection",
    tabLiveSupport: "Live VIP Support",
    categories: {
      "Desserts": "Sweet Desserts & Cakes",
      "Beverages": "Artisanal Drinks & Mixes",
      "Lifestyle": "Traditional Arts & Crafts",
      "Snacks": "Cracker Snacks"
    }
  },
  my: {
    appName: "Sales Brain AI (မြန်မာ)",
    smeHubTab: "အက်စအမ်အီး ဗဟို",
    subtitle: "",
    webhooksActive: "ချိတ်ဆက်မှု အဆင်သင့်ရှိသည်",
    editBusinessProfile: "လုပ်ငန်းအချက်အလက် ပြင်မည်",
    catalogItems: "လက်ရှိပစ္စည်းများ",
    resetDemoState: "စမ်းသပ်မှုစနစ် ပြန်စရန်",
    liveBot: "တယ်လီဂရမ် ဘော့တ်",
    defaultBotWarn: "",
    totalStoreRevenue: "စုစုပေါင်း အရောင်းရငွေ",
    excludesDelivery: "",
    validatedOrders: "အတည်ပြုပြီး အော်ဒါများ",
    cashOnDeliveryAndPrepay: "",
    needsVerification: "စစ်ဆေးရန်လိုအပ်သည်",
    pendingOwnerVerification: "",
    stockWarnings: "ပစ္စည်းအနည်းငယ်သာ ကျန်တော့သည်",
    lowStockMsg: "",
    allInventoriesHealthy: "ကုန်ပစ္စည်း အားလုံး လုံလောက်မှုရှိပါသည်",
    webhookAlertTitle: "ငွေလွှဲဖြတ်ပိုင်းအသစ် ရောက်ရှိလာခြင်း ({count})",
    webhookAlertBody: "စစ်ဆေးရန်လိုအပ်ပါသည်။",
    reviewReceipts: "ဖြတ်ပိုင်းများ အခုပဲ စစ်ဆေးရန်",
    pendingTransactionsLedger: "ငွေလွှဲစစ်ဆေးရန်နှင့် ရောင်းရငွေစာရင်းချုပ်",
    validateSubmittedScreenshots: "",
    exportLedgerCsv: "အော်ဒါစာရင်း CSV ထုတ်ယူရန်",
    orderInvoice: "အော်ဒါ ဘောက်ချာ ID",
    clientCustomer: "ဝယ်သူ အချက်အလက်",
    addressLocation: "လိပ်စာနှင့် ပို့ဆောင်ရန်",
    paymentMethod: "ငွေပေးချေမှုပုံစံ",
    status: "အော်ဒါ အခြေအနေ",
    invoiceSum: "ကျသင့်ငွေ စုစုပေါင်း",
    receiptVerification: "ဖြတ်ပိုင်း အတည်ပြုချက်",
    evaluateReceiptHeader: "ငွေလွှဲဖြတ်ပိုင်း စီစစ်အတည်ပြုခန်း",
    evaluateReceipt: "ဖြတ်ပိုင်းစစ်ဆေးရန်",
    approveCod: "CoD အော်ဒါ အတည်ပြုရန်",
    markCompleted: "ပြီးမြောက်ကြောင်း သတ်မှတ်ရန်",
    noAuditNeeded: "လုပ်ဆောင်ရန် မလိုပါ",
    lowStockTag: "ပစ္စည်းနည်းနေပါသည်",
    unitPriceMmk: "ဈေးနှုန်း (ကျပ်)",
    stockLevel: "လက်ကျန်အရေအတွက်",
    invoiceRef: "ဘောက်ချာ ရည်ညွှန်းချက် ID",
    transactionId: "ငွေလွှဲကုဒ် ID (Transaction ID)",
    paymentChannel: "ငွေပေးချေမှု လမ်းကြောင်း",
    totalCharged: "ကျသင့်ငွေ စုစုပေါင်း",
    confirmGenerateInvoice: "ငွေလွှဲမှန်ကန်ကြောင်း အတည်ပြုပြီး ဘောက်ချာပို့ရန်",
    rejectScreenshot: "ဖြတ်ပိုင်းအချက်အလက်ကို ပယ်ဖျက်ရန်",
    closeEvalPane: "စစ်ဆေးပြီး စာမျက်နှာကိုပိတ်ရန်",
    submittedScreenshotEvidence: "ဝယ်သူပေးပို့လာသည့် ငွေလွှဲဖြတ်ပိုင်း -",
    premiumStoreCatalog: "ရောင်းချနေသည့် ကုန်ပစ္စည်းများစာရင်း",
    controlProductPrices: "",
    addNewProduct: "ကုန်ပစ္စည်းအသစ် ထည့်သွင်းရန်",
    editInfo: "ပြင်ဆင်ရန်",
    delete: "ဖျက်ရန်",
    editProductHeader: "ကုန်ပစ္စည်းအချက်အလက် ပြင်ဆင်ရန်",
    addNewProductHeader: "ကုန်ပစ္စည်းအသစ် ထည့်သွင်းခြင်း",
    brandNameLabel: "ကုန်ပစ္စည်းအမည် -",
    categoryLabel: "အမျိုးအစား သတ်မှတ်ချက် -",
    unitPriceLabel: "သတ်မှတ်စျေးနှုန်း (ကျပ်) -",
    availableStockLabel: "လက်ကျန် အရေအတွက် -",
    imageUrlLabel: "ကုန်ပစ္စည်း ဓာတ်ပုံဖိုင်တင်ရန် -",
    shortDescriptionLabel: "ပစ္စည်း အကျဉ်းချုပ် ဖော်ပြချက် -",
    confirmProductRevisions: "ပြင်ဆင်မှုများအား သိမ်းဆည်းရန်",
    addItemCatalog: "ကုန်ပစ္စည်းစာရင်းထဲ ထည့်မည်",
    townshipDeliveryRateMatrix: "မြို့နယ်အလိုက် ပို့ဆောင်ခ သတ်မှတ်ချက်ဇယား",
    defineDeliveryFees: "",
    townshipNameLabel: "ရန်ကုန်မြို့တွင်း မြို့နယ်အမည် -",
    rateLabel: "နှုန်းထား (ကျပ်) -",
    addRateRule: "နှုန်းထားအသစ် ထည့်သွင်းမည်",
    matchedTownship: "သတ်မှတ်မြို့နယ်",
    estimatedTransit: "ကြာမြင့်ချိန် ခန့်မှန်းချက်",
    settingsActions: "လုပ်ဆောင်ရန်",
    removeRule: "ဖျက်ပစ်ရန်",
    weeklyStoreVolume: "အပတ်စဉ် ရောင်းချရမှု ပမာဏပြဇယား",
    leanAccountingStatsSummary: "ရောင်းရဝင်ငွေ စာရင်းချုပ် အကျဉ်း",
    grossSalesValue: "စုစုပေါင်း ရောင်းရငွေ -",
    ordersCompiled: "စုစုပေါင်း အော်ဒါအရေအတွက် -",
    canceledTransactions: "ပယ်ဖျက်လိုက်သော အော်ဒါများ -",
    downloadLedgerCsv: "ရောင်းအား အချက်အလက် CSV ထုတ်ယူရန်",
    salesBrainAdvisorDesk: "ရောင်းအားမြှင့်တင်ရေး အေအိုင် အကြံပေးခန်း",
    strategicAnalysisPoweredBySparkles: "",
    reEvaluateStrategy: "အကြံပြုချက်ပြန်လည်တွက်ချက်ရန်",
    analyzingPatterns: "အေအိုင်မှ ရောင်းဝယ်မှုပုံစံများကို စီစစ်တွက်ချက်နေပါသည်...",
    telegramBotActivationWorkspace: "တယ်လီဂရမ် Bot စတင်ချိန်ညှိမှု လုပ်ငန်းခွင်",
    oneClickOnboardingDesc: "",
    storeNameLabel: "ဆိုင်အမည် -",
    smeOwnerNameLabel: "ဆိုင်ရှင်အမည် -",
    contactPhoneLabel: "ဆက်သွယ်ရန် ဖုန်းနံပါတ် -",
    customBotTokenLabel: "ရရှိထားသော တယ်လီဂရမ် Bot သော့ချက် (Token ID) -",
    setViaBotFather: "တယ်လီဂရမ် @BotFather တွင် ရယူပါ",
    telegramBotUsernameLabel: "တယ်လီဂရမ် Bot ယူဇာနိမ်း (@) -",
    saveStoreSettingsBtn: "ဆိုင်အချက်အလက် စနစ် သိမ်းဆည်းပြီး တယ်လီဂရမ်နှင့် ချိတ်ဆက်မည်",
    liveSupportRoomHeader: "ဆိုင်ရှင် တိုက်ရိုက် ဝယ်သူစကားပြောခန်း (CRM)",
    chatTakeoverDesc: "",
    activeUserSessionsLabel: "လက်ရှိ စကားပြောနေဆဲ ဝယ်သူများ -",
    supportLabel: "ဆိုင်ရှင်",
    aiAutoLabel: "အေအိုင် ဘော့တ်",
    noMessagesChosen: "ရွေးချယ်ထားသော စကားပြောခြင်း မရှိပါ",
    activeModeLabel: "လက်ရှိစနစ်ပုံစံ -",
    manualSupportOverrideLabel: "ဆိုင်ရှင် တိုက်ရိုက် ဖြေကြားနေသည်",
    automatedBotActiveLabel: "အလိုအလျောက် AI ဖြေကြားနေသည်",
    turnOnAiBotLabel: "AI စနစ်ကို ပြန်ဖွင့်ရန်",
    switchToManualLabel: "ဆိုင်ရှင် တိုက်ရိုက်ဝင်ဖြေရန် (Takeover)",
    ownerChatInputPlaceholder: "ဝယ်သူထံ စာတိုက်ရိုက်ရေးသားရန်...",
    takeoverPlaceholder: "ဝယ်သူနှင့် တိုက်ရိုက်စကားပြောရန် Takeover စနစ်ကို နှိပ်ပါ...",
    sendMessageBtn: "စာပို့ရန်",
    integrationQuickGuidance: "လမ်းညွှန်ချက် အကျဉ်းချုပ်",
    quickGuidanceExplanation: "ဆိုင်ရှင်ဦးစားပေးစနစ်ဖြစ်ပြီး ဘယ်ဘက်ခြမ်းတွင် ဆိုင်အော်ဒါများစစ်ဆေးခြင်း၊ ပစ္စည်းစာရင်းထိန်းချုပ်ခြင်းများ ပြုလုပ်နိုင်ပါသည်။ ညာဘက်ခြမ်း 'စမ်းသပ်ဝယ်ယူသူ စနစ်' ကိုဖွင့်ပြီး တယ်လီဂရမ်ဝယ်ယူမှုပုံစံများကို တိုက်ရိုက်စမ်းသပ်ကြည့်ရှုနိုင်သည်။",
    viewSimulatorButton: "ဝယ်သူစုံစမ်းစမ်းသပ်ခန်း အသုံးပြုရန်",
    closeSimulatorButton: "စမ်းသပ်ခန်းပြန်သိမ်းရန်",
    simulationSandboxTitle: "တယ်လီဂရမ် ဝယ်သူ စမ်းသပ်ဝယ်ယူမှု စနစ်",
    chooseLanguageLabel: "Language / ဘာသာစကား",
    tabOrders: "အော်ဒါမှတ်တမ်း",
    tabProducts: "ကုန်ပစ္စည်းများ",
    tabDelivery: "ပို့ဆောင်ခနှုန်းထား",
    tabInsights: "မဟာဗျူဟာ (AI)",
    tabSmartMarketing: "မားကက်တင်း (AI)",
    tabConfig: "ဘော့တ်ချိတ်ဆက်မှု",
    tabLiveSupport: "VIP တိုက်ရိုက်ပြောခန်း",
    categories: {
      "Desserts": "အချိုပွဲနှင့် မုန့်မျိုးစုံ",
      "Beverages": "လက်လုပ်ဖျော်ရည်နှင့် အဖျော်ယမကာ",
      "Lifestyle": "ရိုးရာအနုပညာနှင့် လက်မှုပစ္စည်း",
      "Snacks": "အကြွပ်မုန့်မျိုးစုံ"
    }
  }
};
